;========================================
; Resources Drive Setup
;========================================

[Network]
SERVER=DBC-00
SHARE=Resources
DRIVE=R

[Application]
APPNAME=Resources Drive Setup
COMPANY=DBC Computer Lab

[Task]
TASKNAME=Resources Drive Mapper

[Shortcut]
NAME=Resources