name: Build Resources Drive

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Compile Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer\ResourcesDriveSetup.iss

        shell: powershell

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ResourcesDriveSetup
          path: Installer/Output/ResourcesDriveSetup.exe